### ISSUE TITLE
Garbage on LineNumbersRuler under Java 11+ on Windows with HiDPI monitor support

### ISSUE THREAD

**Issue by dpolivaev** [Sciss/SyntaxPane#36]
Attempt to fill component background leads to garbage shown in the attached picture:
![javaw_2022-04-10_18-49-25](https://user-images.githubusercontent.com/1558052/162630518-ddd379d7-41ca-4c76-9a61-0e43359eb23f.png)

The problem can be fixed by assigning constant value `LineNumbersRuler.MAX_HEIGHT` a smaller number e.g. 100000 instead of  currently used `Integer.MAX_VALUE - 1000000`.

Even if it is a Java failure because the painter ignores the clip bounds I think you can fix it easier on your side.

I could reproduce it with Java 11, Java 15 and Java 17

**Comment by dpolivaev** [comment]
I think that using big numbers might produce integer overflows when they are multiplied by monitor resolution related screen scaling factors

**Comment by Sciss** [comment]
Thank you, a fix is on the way as v1.2.1.
